focus/urls.py
from django.conf.urls import url
from . import views
from .forms import StepOneForm, StepTwoForm, StepThreeForm

app_name = 'focus'
urlpatterns = [
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^home/$', views.IndexView.as_view(), name='index'),
    url(r'^$', views.login_view, name='login'),
    url(r'^page/(?P<page>[0-9]+)/$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^category/(?P<pk>[0-9]+)/page/(?P<page>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    url(r'^tag/(?P<pk>[0-9]+)/page/(?P<page>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    url(r'^u/(?P<pk>\d+)/$', views.user_info, name='user_info'),
    url(r'^u/(?P<pk>\d+)/topics/page/(?P<page>[0-9]+)/$', views.UserTopics.as_view(), name='user_posts'),
    url(r'^u/(?P<pk>\d+)/topics/$', views.UserTopics.as_view(), name='user_posts'),
    url(r'^post/create/$', views.SheetWizard.as_view([StepOneForm, StepTwoForm, StepThreeForm]), name='create_post'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.edit_post, name='edit_post'),
    # url(r'^search/$', views.search, name='search'),
    url(r'^test/$', views.SheetWizard.as_view([StepOneForm, StepTwoForm, StepThreeForm]), name='test'),
]

telinfo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.http import HttpResponse

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('focus.urls')),
    url(r'', include('comments.urls')),
    url(r'^robots\.txt$', lambda r: HttpResponse('User-agent: *\nDisallow: /', content_type='text/plain')),
    url(r'^search/', include('haystack.urls')),
]

comments/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import User


# python_2_unicode_compatible 装饰器用于兼容 Python2
@python_2_unicode_compatible
class Comment(models.Model):
    user = models.ForeignKey(User)
    post = models.ForeignKey('focus.Post', null=True)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True, editable=True)

    def __str__(self):
        return self.content

focus/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import markdown
from django.utils.html import strip_tags


class PostManager(models.Manager):

    def query_by_column(self, category_id):
        query = self.get_queryset().filter(category_id=category_id)
        return query

    def query_by_user(self, user_id):
        user = User.objects.get(id=user_id)
        article_list = user.article_set.all()
        return article_list

    def query_by_polls(self):
        query = self.get_queryset().order_by('views')
        return query

    def query_by_time(self):
        query = self.get_queryset().order_by('-pub_date')
        return query

    def query_by_keyword(self, keyword):
        query = self.get_queryset().filter(title__contains=keyword)
        return query


@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField('category_name', max_length=256)
    intro = models.TextField('introduction', default='')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'category'
        ordering = ['name']


@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Post(models.Model):
    category = models.ForeignKey(Category, verbose_name='belong to')
    tags = models.ManyToManyField(Tag, blank=True)
    title = models.CharField(max_length=256)

    record_id = models.CharField(max_length=14)
    company_name = models.CharField(max_length=256)
    tel_no = models.CharField(max_length=20)
    consultee = models.CharField(max_length=20, blank=True)
    content = models.TextField('content')
    assign_person = models.CharField(max_length=20, blank=True)
    result = models.CharField(max_length=50, blank=True)
    pricing = models.CharField(max_length=20, blank=True)
    published = models.BooleanField('notDraft', default=False)
    author = models.ForeignKey(User, verbose_name="user")
    pub_date = models.DateTimeField(auto_now_add=True, editable=True)
    update_time = models.DateTimeField(auto_now=True, null=True)
    remarks = models.TextField('remarks', blank=True)

    excerpt = models.CharField(max_length=200, blank=True)
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

        # 自定义 get_absolute_url 方法
        # 记得从 django.urls 中导入 reverse 函数
    def get_absolute_url(self):
            return reverse('focus:detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'post'
        ordering = ['-pub_date']

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        # 如果没有填写摘要
        if not self.excerpt:
            # 首先实例化一个 Markdown 类，用于渲染 body 的文本
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            # 先将 Markdown 文本渲染成 HTML 文本
            # strip_tags 去掉 HTML 文本的全部 HTML 标签
            # 从文本摘取前 54 个字符赋给 excerpt
            self.excerpt = strip_tags(md.convert(self.content))[:54]

        # 调用父类的 save 方法将数据保存到数据库中
        super(Post, self).save(*args, **kwargs)

    objects = PostManager()


class PostQueryset(models.QuerySet):

    def visible(self):
        return self.filter(hidden=False)

focus/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import markdown
from markdown.extensions.toc import TocExtension
from django.utils.text import slugify
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.core.urlresolvers import reverse
from django.utils.decorators import method_decorator
from .forms import LoginForm, PostForm, PostEditForm, StepOneForm
from .models import Post, Category, Tag
from comments.forms import CommentForm
from comments.models import Comment
from django.db.models import Q
from formtools.wizard.views import SessionWizardView

User = get_user_model()


# Create your views here.


class IndexView(ListView):
    model = Post
    template_name = 'view/index_new.html'
    context_object_name = 'post_list'

    def get_context_data(self, **kwargs):
        """
        在视图函数中将模板变量传递给模板是通过给 render 函数的 context 参数传递一个字典实现的，
        例如 render(request, 'blog/index.html', context={'post_list': post_list})，
        这里传递了一个 {'post_list': post_list} 字典给模板。
        在类视图中，这个需要传递的模板变量字典是通过 get_context_data 获得的，
        所以我们复写该方法，以便我们能够自己再插入一些我们自定义的模板变量进去。
        """

        # 首先获得父类生成的传递给模板的字典。
        context = super(IndexView, self).get_context_data(**kwargs)
        context['panel_title'] = 'New Posts'
        context['show_order'] = True
        if not is_viewer(self.request.user, 'record_viewer'):
            context['post_list'] = Post.objects.filter(Q(author=self.request.user) | Q(published='1'))
        return context

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(IndexView, self).dispatch(request, *args, **kwargs)


# 记得在顶部导入 DetailView
class PostDetailView(DetailView):
    # 这些属性的含义和 ListView 是一样的
    model = Post
    template_name = 'view/detail_new.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        response = super(PostDetailView, self).get(request, *args, **kwargs)

        # 将文章阅读量 +1
        # 注意 self.object 的值就是被访问的文章 post
        self.object.increase_views()

        # 视图必须返回一个 HttpResponse 对象
        return response

    def get_object(self, queryset=None):
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        post = super(PostDetailView, self).get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify=slugify),
        ])
        post.body = md.convert(post.content)
        post.toc = md.toc
        return post

    def get_context_data(self, **kwargs):
        # 覆写 get_context_data 的目的是因为除了将 post 传递给模板外（DetailView 已经帮我们完成），
        # 还要把评论表单、post 下的评论列表传递给模板。
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list
        })
        return context

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        current = Post.objects.get(pk=self.kwargs.get('pk'))
        post_id = self.kwargs.get('pk')
        form = CommentForm(
            request.POST,
            user=request.user,
            post_id=post_id
        )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(
                reverse('focus:detail', kwargs={'pk': post_id})
            )

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(PostDetailView, self).dispatch(request, *args, **kwargs)


class ArchivesView(ListView):
    model = Post
    template_name = 'view/index_new.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchivesView, self).get_queryset().filter(pub_date__year=year,
                                                               pub_date__month=month
                                                               )

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ArchivesView, self).dispatch(request, *args, **kwargs)


class CategoryView(ListView):
    model = Post
    template_name = 'view/index_new.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        if is_viewer(self.request.user, 'record_viewer'):
            return super(CategoryView, self).get_queryset().filter(category=cate)
        else:
            return super(CategoryView, self).get_queryset().filter(Q(category=cate),
                                                                   Q(author=self.request.user) | Q(published='1'))

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(CategoryView, self).dispatch(request, *args, **kwargs)


class TagView(ListView):
    model = Post
    template_name = 'view/index_new.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        if is_viewer(self.request.user, 'record_viewer'):
            return super(TagView, self).get_queryset().filter(tags=tag)
        else:
            return super(TagView, self).get_queryset().filter(Q(tags=tag),
                                                              Q(author=self.request.user) | Q(published='1'))

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(TagView, self).dispatch(request, *args, **kwargs)


def login_view(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('focus:index'))
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'login_new.html', {'form': form})
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        valid = True
        if not username or not password:
            valid = False
            messages.add_message(request, messages.INFO, 'Username and password cannot be empty')
        user = User.objects.filter(username=username).first()
        if not user:
            valid = False
            messages.add_message(request, messages.INFO, 'User does not exist')
        user = authenticate(username=username, password=password)
        if (user is not None) and valid:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('focus:index'))
            else:
                valid = False
                messages.add_message(request, messages.INFO, 'User deactivated')
        else:
            valid = False
            messages.add_message(request, messages.INFO, 'Incorrect password')
        if not valid:
            return HttpResponseRedirect(reverse('focus:login'))


@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('focus:login'))


@login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, user=request.user)
        if form.is_valid():
            t = form.save(commit=False)
            t.author = request.user
            t.save()
        return HttpResponseRedirect(reverse('focus:detail', kwargs={'pk': t.pk}))
    else:
        form = PostForm()

    return render(request, 'create_post_new.html', {'form': form, 'title': 'Create Post'})


@login_required
def edit_post(request, pk):
    post = Post.objects.get(pk=pk)
    if post.published:
        return HttpResponseForbidden('Editing is not allowed when post has been published')
    if not post.author == request.user:
        return HttpResponseForbidden('You are not allowed to edit other\'s post')
    if request.method == 'POST':
        form = PostEditForm(request.POST, instance=post)
        if form.is_valid():
            t = form.save()
            return HttpResponseRedirect(reverse('focus:detail', kwargs={'pk': t.pk}))
    else:
        form = PostEditForm(instance=post)

    return render(request, 'edit_post_new.html', {'form': form, 'title': 'Edit Post'})


@login_required
def user_info(request, pk):
    u = User.objects.get(pk=pk)
    if is_viewer(u, 'record_viewer'):
        return render(request, 'user_info.html', {
            'title': u.username,
            'user': u,
            'posts': u.post_set.select_related('category')[:10],
            'comments': u.comment_set.select_related('post', 'user').order_by('-pub_date')[:10],
        })
    else:
        return render(request, 'user_info_new.html', {
            'title': u.username,
            'user': u,
            'posts': u.post_set.filter(Q(published='1') | Q(author=request.user)).select_related('category')[:10],
            'comments': u.comment_set.select_related('post', 'user').order_by('-pub_date')[:10],
        })


class UserTopics(ListView):
    model = Comment
    template_name = 'user_posts_new.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        if is_viewer(self.request.user, 'record_viewer'):
            return Post.objects.filter(
                author_id=self.kwargs.get('pk')
            ).select_related(
                'author', 'category'
            )
        else:

focus/templates/base_new.html
<!DOCTYPE html>
<html class="no-js">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PHONE RECORD</title>
    {% load staticfiles %}
    {% load blog_tags %}
    <!-- Bootstrap -->
    <link href="{% static "bootstrap/css/bootstrap.min.css"%}" rel="stylesheet" media="screen">
    <link href="{% static "bootstrap/css/bootstrap-responsive.min.css"%}" rel="stylesheet" media="screen">
    <link href="{% static "assets/styles.css"%}" rel="stylesheet" media="screen">
    <link href="{% static "assets/DT_bootstrap.css"%}" rel="stylesheet" media="screen">
    <link href="{% static "assets/buttons.dataTables.min.css"%}" rel="stylesheet" media="screen">
    <link href="{% static "assets/ace.css"%}" rel="stylesheet" class="ace-main-stylesheet" id="main-ace-style" />
    <!--[if lte IE 8]>
        <script language="javascript" type="text/javascript" src="{% static "vendors/flot/excanvas.min.js"%}"></script>
    <![endif]-->
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script src="{% static "vendors/modernizr-2.6.2-respond-1.1.0.min.js"%}"></script>
</head>

<body>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
                </a>
                <a class="brand" href="#">Phone Record</a>
                <div class="nav-collapse collapse">
                    <ul class="nav pull-right">
                        <li class="dropdown">
                            <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"> <i class="icon-user"></i>{{ request.user.username }} <i class="caret"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a tabindex="-1" href="{% url 'focus:user_info' request.user.pk %}">Profile</a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a tabindex="-1" href="{% url 'focus:logout' %}">登出</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="nav">
                        <li class="active">
                            <a href="{% url 'focus:index' %}">Index</a>
                        </li>
                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle">Settings <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu" id="menu1">
                                <li>
                                    <a href="#">Tools <i class="icon-arrow-right"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">Other Link</a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="#">Other Link</a>
                                </li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">Content <i class="caret"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a tabindex="-1" href="#">News</a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a tabindex="-1" href="#">FAQ</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span3" id="sidebar">
                <ul class="nav nav-list bs-docs-sidenav nav-collapse collapse">
                    <li>
                        <a href="{% url 'focus:index' %}"><i class="icon-chevron-right"></i> 列表</a>
                    </li>
                    <li>
                        <a href="{% url 'focus:create_post' %}"><i class="icon-chevron-right"></i> 新建</a>
                    </li>
                    <li>
                        <a href="#"> 最新记录<span class="badge badge-success pull-right">5</span></a>
                        {% get_recent_posts request as recent_post_list %}
                        <ul>
                            {% for post in recent_post_list %}
                            <li>
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </li>
                            {% empty %}
                                暂无记录！
                            {% endfor %}
                        </ul>
                    </li>
                    <li>{% archives as date_list %}
                        <a href="#"> 归档<span class="badge badge-info pull-right">{{ date_list.count }}</span></a>
                        <ul>
                            {% for date in date_list %}
                                <li>
                                    <a href="{% url 'focus:archives' date.year date.month %}">{{ date.year }}
                                        年 {{ date.month }} 月</a>
                                </li>
                            {% empty %}
                                暂无归档！
                            {% endfor %}
                        </ul>
                    </li>
                    <li>{% get_categories request as category_list %}
                        <a href="#"> 分类<span class="badge badge-important pull-right">{{ category_list.count }}</span></a>
                        <ul>
                            {% for category in category_list %}
                                <li>
                                    <a href="{% url 'focus:category' category.pk %}">{{ category.name }} <span
                                            class="post-count">({{ category.num_posts }})</span></a>
                                </li>
                            {% empty %}
                                暂无分类！
                            {% endfor %}
                        </ul>
                    </li>
                    <li>{% get_tags as tag_list %}
                        <a href="#"> 标签云<span class="badge badge-warning pull-right">{{ tag_list.count }}</span></a>
                        <ul>
                            {% for tag in tag_list %}
                                <li>
                                    <a href="{% url 'focus:tag' tag.pk %}">{{ tag.name }}</a>
                                </li>
                            {% empty %}
                                暂无标签！
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
            </div>

            <!--/span-->
            <div class="span9" id="content">
                <div class="row-fluid">
                    <div class="block">
                    {% block main %}
                    {% endblock main %}
                    </div>
                </div>
            </div>
            <div class="span9" id="content">
                <div class="row-fluid">
                    <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                            target="_blank" title="模板之家">模板之家</a>
                        - 由<a href="http://www.sjd-logistics.com/" title="网页模板" target="_blank">景鸿物流修改</a>
                    </p>
                </div>
            </div>
        </div>

    </div>
    <!--/.fluid-container-->
    <script src="{% static "vendors/jquery-1.9.1.min.js"%}"></script>
    <script src="{% static "vendors/jquery.maskedinput.js"%}"></script>
    <script src="{% static "bootstrap/js/bootstrap.min.js"%}"></script>
    <script src="{% static "vendors/datatables/js/jquery.dataTables.min.js"%}"></script>
    <script src="{% static "assets/DT_bootstrap.js"%}"></script>
    <script src="{% static "assets/dataTables.buttons.min.js"%}"></script>
    <script src="{% static "assets/buttons.flash.min.js"%}"></script>
    <script src="{% static "assets/jszip.min.js"%}"></script>
    <script src="{% static "assets/buttons.html5.min.js"%}"></script>
    <script src="{% static "assets/buttons.print.min.js"%}"></script>
    <script src="{% static "assets/buttons.colVis.min.js"%}"></script>
    <script src="{% static "assets/scripts.js"%}"></script>
    <script type="text/javascript">
    jQuery(function ($){
        $('.input-mask-phone').mask('(999) 9999-9999');
    });
    </script>
</body>

</html>

focus/templates/create_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
    <div class="panel panel-default">
        <div class="panel-body">
            <form method="post" action="{% url "focus:create_post" %}">
                {% crispy form %}
            </form>
        </div>
    </div>
{% endblock %}

focus/templates/user_info_new.html
{% extends 'base_new.html' %}
{% load humanize %}
{% load blog_tags %}

{% block main %}
    {% if error_msg %}
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
                <h4>Error</h4>
                    {{ error_msg }}</div>
    {% endif %}
    <div class="navbar">
        <div class="navbar-inner">
            <ul class="breadcrumb">
                <i class="icon-chevron-left hide-sidebar"><a href='#' title="Hide Sidebar" rel='tooltip'>&nbsp;</a></i>
                <i class="icon-chevron-right show-sidebar" style="display:none;"><a href='#' title="Show Sidebar" rel='tooltip'>&nbsp;</a></i>
                <li>
                    <a href="{% url 'focus:index' %}">Home</a> <span class="divider">/</span>
                </li>
                <li class="active">{{ user.username }}创建的记录</li>
            </ul>
        </div>
    </div>
    {% include 'widgets/user_info_panel_new.html' %}
    <div class="block-content collapse in">
        <div class="span12">
        <!-- List group -->
            <div>
                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example2">
                    <thead>
                        <tr>
                            <th>记录号</th>
                            <th>行业</th>
                            <th>公司</th>
                            <th>业务范围</th>
                            <th>咨询主旨</th>
                            <th>咨询结果</th>
                            <th>价单</th>
                            <th>创建人</th>
                            <th>创建日期</th>
                            <th>评论</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for post in posts %}
                            <tr class="odd gradeA">
                                <td class="center">{{ post.record_id }}</td>
                                <td><a href="{% url 'focus:category' post.category.pk %}">
                                        {{ post.category.name }}
                                    </a></td>
                                <td class="center">{{ post.company_name }}</td>
                                <td class="center">
                                    {% for name in post.tags.all %}
                                        {{ name }}
                                    {% endfor %}</td>
                                <td><a href="{% url 'focus:detail' pk=post.pk %}" class="entry-link">
                                        {{ post.title }}
                                    </a>
                                </td>
                                <td class="center">{{ post.result }}</td>
                                <td class="center">{{ post.pricing }}</td>
                                <td><a href="{% url 'focus:user_info' post.author.pk %}">
                                        {{ post.author.username }}
                                    </a></td>
                                <td class="center">{{ post.pub_date | date:"Y-m-d H:i:s" }}</td>
                                <td><span class="badge badge-info">{{ post.comment_set.count }}</span></td>
                            </tr>
                            {% empty %}
                            <div>暂时还没有发布的信息！</div>
                            {% endfor %}
                    </tbody>
                </table>
            </div>
            <li class="list-group-item">
                <a href="{% url 'focus:user_posts' user.pk %}" class="text-success">More posts from this user</a>
            </li>
        </div>
    </div>
    <div class="block-content collapse in">
        <div class="span12">
            <div class="widget-box transparent">
                <div class="widget-header widget-header-small">
                    <h4 class="widget-title blue smaller">
                        <i class="icon-edit"></i>
                        来自{{ user.username }}的评论
                    </h4>
                </div>
                <div class="widget-body">
                    <div class="widget-main padding-8">
                        <!-- #section:pages/profile.feed -->
                        <div id="profile-feed-1" class="profile-feed">
                            <div class="profile-activity clearfix">
                                <div>
                                {% if comments.count %}
                                    {% for comment in comments %}
                                        Commented to
                                        <a class="user" href="{% url 'focus:detail' pk=comment.post.pk %}">{{ comment.post.title }}</a>
                                        <div>{{ comment.content | safe}}</div>
                                        <div class="time">
                                            <i class="ace-icon fa fa-clock-o bigger-110"></i>
                                            {{ comment.pub_date | naturaltime }}
                                        </div>
                                        <div class="space-12"></div>
                                    {% endfor %}
                                {% else %}
                                    {% if not comments %}
                                        <li class="list-group-item comment-item">此用户还没有评论!</li>
                                    {% endif %}
                                {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}