focus/urls.py
from django.conf.urls import url
from . import views
from .forms import StepOneForm, StepTwoForm, StepThreeForm

app_name = 'focus'
urlpatterns = [
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^home/$', views.IndexView.as_view(), name='index'),
    url(r'^$', views.login_view, name='login'),
    url(r'^page/(?P<page>[0-9]+)/$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^category/(?P<pk>[0-9]+)/page/(?P<page>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    url(r'^tag/(?P<pk>[0-9]+)/page/(?P<page>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    url(r'^u/(?P<pk>\d+)/$', views.user_info, name='user_info'),
    url(r'^u/(?P<pk>\d+)/topics/page/(?P<page>[0-9]+)/$', views.UserTopics.as_view(), name='user_posts'),
    url(r'^u/(?P<pk>\d+)/topics/$', views.UserTopics.as_view(), name='user_posts'),
    url(r'^post/create/$', views.SheetWizard.as_view([StepOneForm, StepTwoForm, StepThreeForm]), name='create_post'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.edit_post, name='edit_post'),
    # url(r'^search/$', views.search, name='search'),
    url(r'^test/$', views.SheetWizard.as_view([StepOneForm, StepTwoForm, StepThreeForm]), name='test'),
]

telinfo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.http import HttpResponse

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('focus.urls')),
    url(r'', include('comments.urls')),
    url(r'^robots\.txt$', lambda r: HttpResponse('User-agent: *\nDisallow: /', content_type='text/plain')),
    url(r'^search/', include('haystack.urls')),
]

comments/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import User


# python_2_unicode_compatible 装饰器用于兼容 Python2
@python_2_unicode_compatible
class Comment(models.Model):
    user = models.ForeignKey(User)
    post = models.ForeignKey('focus.Post', null=True)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True, editable=True)

    def __str__(self):
        return self.content

focus/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import markdown
from django.utils.html import strip_tags


class PostManager(models.Manager):

    def query_by_column(self, category_id):
        query = self.get_queryset().filter(category_id=category_id)
        return query

    def query_by_user(self, user_id):
        user = User.objects.get(id=user_id)
        article_list = user.article_set.all()
        return article_list

    def query_by_polls(self):
        query = self.get_queryset().order_by('views')
        return query

    def query_by_time(self):
        query = self.get_queryset().order_by('-pub_date')
        return query

    def query_by_keyword(self, keyword):
        query = self.get_queryset().filter(title__contains=keyword)
        return query


@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField('category_name', max_length=256)
    intro = models.TextField('introduction', default='')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'category'
        ordering = ['name']


@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Post(models.Model):
    category = models.ForeignKey(Category, verbose_name='belong to')
    tags = models.ManyToManyField(Tag, blank=True)
    title = models.CharField(max_length=256)

    record_id = models.CharField(max_length=14)
    company_name = models.CharField(max_length=256)
    tel_no = models.CharField(max_length=20)
    consultee = models.CharField(max_length=20, blank=True)
    content = models.TextField('content')
    assign_person = models.CharField(max_length=20, blank=True)
    result = models.CharField(max_length=50, blank=True)
    pricing = models.CharField(max_length=20, blank=True)
    published = models.BooleanField('notDraft', default=False)
    author = models.ForeignKey(User, verbose_name="user")
    pub_date = models.DateTimeField(auto_now_add=True, editable=True)
    update_time = models.DateTimeField(auto_now=True, null=True)
    remarks = models.TextField('remarks', blank=True)

    excerpt = models.CharField(max_length=200, blank=True)
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

        # 自定义 get_absolute_url 方法
        # 记得从 django.urls 中导入 reverse 函数
    def get_absolute_url(self):
            return reverse('focus:detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'post'
        ordering = ['-pub_date']

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        # 如果没有填写摘要
        if not self.excerpt:
            # 首先实例化一个 Markdown 类，用于渲染 body 的文本
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            # 先将 Markdown 文本渲染成 HTML 文本
            # strip_tags 去掉 HTML 文本的全部 HTML 标签
            # 从文本摘取前 54 个字符赋给 excerpt
            self.excerpt = strip_tags(md.convert(self.content))[:54]

        # 调用父类的 save 方法将数据保存到数据库中
        super(Post, self).save(*args, **kwargs)

    objects = PostManager()


class PostQueryset(models.QuerySet):

    def visible(self):
        return self.filter(hidden=False)

focus/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import markdown
from markdown.extensions.toc import TocExtension
from django.utils.text import slugify
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.core.urlresolvers import reverse
from django.utils.decorators import method_decorator
from .forms import LoginForm, PostForm, PostEditForm, StepOneForm
from .models import Post, Category, Tag
from comments.forms import CommentForm
from comments.models import Comment
from django.db.models import Q
from formtools.wizard.views import SessionWizardView

User = get_user_model()


# Create your views here.


class IndexView(ListView):
    model = Post
    template_name = 'view/index_new.html'
    context_object_name = 'post_list'

    def get_context_data(self, **kwargs):
        """
        在视图函数中将模板变量传递给模板是通过给 render 函数的 context 参数传递一个字典实现的，
        例如 render(request, 'blog/index.html', context={'post_list': post_list})，
        这里传递了一个 {'post_list': post_list} 字典给模板。
        在类视图中，这个需要传递的模板变量字典是通过 get_context_data 获得的，
        所以我们复写该方法，以便我们能够自己再插入一些我们自定义的模板变量进去。
        """

        # 首先获得父类生成的传递给模板的字典。
        context = super(IndexView, self).get_context_data(**kwargs)
        context['panel_title'] = 'New Posts'
        context['show_order'] = True
        if not is_viewer(self.request.user, 'record_viewer'):
            context['post_list'] = Post.objects.filter(Q(author=self.request.user) | Q(published='1'))
        return context

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(IndexView, self).dispatch(request, *args, **kwargs)


# 记得在顶部导入 DetailView
class PostDetailView(DetailView):
    # 这些属性的含义和 ListView 是一样的
    model = Post
    template_name = 'view/detail_new.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        response = super(PostDetailView, self).get(request, *args, **kwargs)

        # 将文章阅读量 +1
        # 注意 self.object 的值就是被访问的文章 post
        self.object.increase_views()

        # 视图必须返回一个 HttpResponse 对象
        return response

    def get_object(self, queryset=None):
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        post = super(PostDetailView, self).get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify=slugify),
        ])
        post.body = md.convert(post.content)
        post.toc = md.toc
        return post

    def get_context_data(self, **kwargs):
        # 覆写 get_context_data 的目的是因为除了将 post 传递给模板外（DetailView 已经帮我们完成），
        # 还要把评论表单、post 下的评论列表传递给模板。
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list
        })
        return context

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        current = Post.objects.get(pk=self.kwargs.get('pk'))
        post_id = self.kwargs.get('pk')
        form = CommentForm(
            request.POST,
            user=request.user,
            post_id=post_id
        )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(
                reverse('focus:detail', kwargs={'pk': post_id})
            )

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(PostDetailView, self).dispatch(request, *args, **kwargs)


class ArchivesView(ListView):
    model = Post
    template_name = 'view/index_new.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchivesView, self).get_queryset().filter(pub_date__year=year,
                                                               pub_date__month=month
                                                               )

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ArchivesView, self).dispatch(request, *args, **kwargs)


class CategoryView(ListView):
    model = Post
    template_name = 'view/index_new.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        if is_viewer(self.request.user, 'record_viewer'):
            return super(CategoryView, self).get_queryset().filter(category=cate)
        else:
            return super(CategoryView, self).get_queryset().filter(Q(category=cate),
                                                                   Q(author=self.request.user) | Q(published='1'))

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(CategoryView, self).dispatch(request, *args, **kwargs)


class TagView(ListView):
    model = Post
    template_name = 'view/index_new.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        if is_viewer(self.request.user, 'record_viewer'):
            return super(TagView, self).get_queryset().filter(tags=tag)
        else:
            return super(TagView, self).get_queryset().filter(Q(tags=tag),
                                                              Q(author=self.request.user) | Q(published='1'))

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(TagView, self).dispatch(request, *args, **kwargs)


def login_view(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('focus:index'))
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'login_new.html', {'form': form})
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        valid = True
        if not username or not password:
            valid = False
            messages.add_message(request, messages.INFO, 'Username and password cannot be empty')
        user = User.objects.filter(username=username).first()
        if not user:
            valid = False
            messages.add_message(request, messages.INFO, 'User does not exist')
        user = authenticate(username=username, password=password)
        if (user is not None) and valid:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('focus:index'))
            else:
                valid = False
                messages.add_message(request, messages.INFO, 'User deactivated')
        else:
            valid = False
            messages.add_message(request, messages.INFO, 'Incorrect password')
        if not valid:
            return HttpResponseRedirect(reverse('focus:login'))


@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('focus:login'))


@login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, user=request.user)
        if form.is_valid():
            t = form.save(commit=False)
            t.author = request.user
            t.save()
        return HttpResponseRedirect(reverse('focus:detail', kwargs={'pk': t.pk}))
    else:
        form = PostForm()

    return render(request, 'create_post_new.html', {'form': form, 'title': 'Create Post'})


@login_required
def edit_post(request, pk):
    post = Post.objects.get(pk=pk)
    if post.published:
        return HttpResponseForbidden('Editing is not allowed when post has been published')
    if not post.author == request.user:
        return HttpResponseForbidden('You are not allowed to edit other\'s post')
    if request.method == 'POST':
        form = PostEditForm(request.POST, instance=post)
        if form.is_valid():
            t = form.save()
            return HttpResponseRedirect(reverse('focus:detail', kwargs={'pk': t.pk}))
    else:
        form = PostEditForm(instance=post)

    return render(request, 'edit_post_new.html', {'form': form, 'title': 'Edit Post'})


@login_required
def user_info(request, pk):
    u = User.objects.get(pk=pk)
    if is_viewer(u, 'record_viewer'):
        return render(request, 'user_info.html', {
            'title': u.username,
            'user': u,
            'posts': u.post_set.select_related('category')[:10],
            'comments': u.comment_set.select_related('post', 'user').order_by('-pub_date')[:10],
        })
    else:
        return render(request, 'user_info_new.html', {
            'title': u.username,
            'user': u,
            'posts': u.post_set.filter(Q(published='1') | Q(author=request.user)).select_related('category')[:10],
            'comments': u.comment_set.select_related('post', 'user').order_by('-pub_date')[:10],
        })


class UserTopics(ListView):
    model = Comment
    template_name = 'user_posts_new.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        if is_viewer(self.request.user, 'record_viewer'):
            return Post.objects.filter(
                author_id=self.kwargs.get('pk')
            ).select_related(
                'author', 'category'
            )
        else:

focus/templates/view/detail.html
{% extends 'base.html' %}
{% load blog_tags %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block main %}
    <div class="panel panel-default">
     <!-- Default panel contents -->
        <div class="panel-body">
            <ol class="breadcrumb">
                <li><a href="{% url 'focus:index' %}">Home</a></li>
                <li><a href="{% url 'focus:category' pk=post.category.pk %}">{{ post.category.name }}</a></li>
                <li class="active">{{ post.title }}</li>
            </ol>
            <h1 class="post-title">{{ post.title }}</h1>
            <div class="post-meta row">
                <div class="col-xs-9 col-sm-10">
                    <p class="text-muted">
                        <a href="{% url 'focus:user_info' post.author.pk %}">{{ post.author.username }}</a>
                        <br/>
                        <span>Posted {{ post.pub_date | naturaltime }} in <a class="text-primary" href="{% url 'focus:category' pk=post.category.pk %}">{{ post.category.name }}</a>, </span>
                        <span>Viewed {{ post.views }} times</span>
                    </p>
                </div>
            </div>
            <div class="post-content">
                <p>{{ post.content | safe}}</p>
            </div>
        </div>
        {% if request.user == post.author %}
            <div class="panel-footer">
                {% if not post.published %}
                    <a href="{% url 'focus:edit_post' pk=post.pk %}"><span class="label label-success">Edit</span></a>
                {% endif %}
            </div>
        {% endif %}
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            {% if post.comment_set.count %}
                {{ post.comment_set.count }} Reply {{ post.comment_set.count }} Replies
            {% else %}
                No Comments
            {% endif %}
        </div>
        <!-- List group -->
        <ul class="list-group comment-list">
            {% for comment in comment_list %}
                <li class="list-group-item comment-item">
                    <div class="post-meta row">
                        <div class="col-xs-9 col-sm-10">
                            <p class="text-muted">
                                <a href="{% url 'focus:user_info' comment.user_id %}">{{ comment.user }}</a> <br/>
                                <span>{{ comment.pub_date | naturaltime }}</span>
                            </p>
                        </div>
                    </div>
                    <div class="comment-content">
                        <p>
                            {{ comment.content | safe}}
                        </p>
                    </div>
                    <p class="comment-link">
                        <a href="#" data-username="{{ comment.user.username }}" class="reply-to">Reply</a>
                    </p>
                </li>
            {% endfor %}
            {% if not comment_list %}
                <li class="list-group-item comment-item"><p>Be the first to reply!</p></li>
            {% endif %}
        </ul>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">Leave a Comment</div>
        <div class="panel-body">
            {% if request.user.is_authenticated %}
                <form action="{% url 'focus:detail' pk=post.pk %}" method="POST">
                    {% crispy form %}
                </form>
            {% else %}
                <div class="alert alert-warning" role="alert">
                    {% url login_url_name as login_url %}
                        Please <a href="{{ login_url }}">Login</a> to comment
                </div>
            {% endif %}
        </div>
    </div>
{% endblock main %}

focus/templates/view/detail_new.html
{% extends 'base_new.html' %}
{% load blog_tags %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block main %}
    {% if error_msg %}
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
                <h4>Error</h4>
                    {{ error_msg }}</div>
    {% endif %}
    {% block before_main_left %}{% endblock %}
    <div class="navbar">
        <div class="navbar-inner">
            <ul class="breadcrumb">
                <i class="icon-chevron-left hide-sidebar"><a href='#' title="Hide Sidebar" rel='tooltip'>&nbsp;</a></i>
                <i class="icon-chevron-right show-sidebar" style="display:none;"><a href='#' title="Show Sidebar" rel='tooltip'>&nbsp;</a></i>
                <li>
                    <a href="{% url 'focus:index' %}">Home</a> <span class="divider">/</span>
                </li>
                <li><a href="{% url 'focus:category' pk=post.category.pk %}">{{ post.category.name }}</a><span class="divider">/</span></li>
                <li class="active">{{ post.title }}</li>
            </ul>
        </div>
    </div>
    <div class="block-content collapse in">
        <div class="span12">
            <div class="page-header">
                <h1>
                    咨询详情
                    <small>
                        <i class="icon-chevron-right"></i>
                            {{ post.title }}
                    </small>
                </h1>
            </div><!-- /.page-header -->
            <div class="col-xs-12 col-sm-9">
                <div class="profile-user-info profile-user-info-striped">
                    <div class="profile-info-row">
                        <div class="profile-info-name"> 记录流水号 </div>
                        <div class="profile-info-value">
                            <span id="username">{{ post.record_id }}</span>
                        </div>
                    </div>
                    <div class="profile-info-row">
                        <div class="profile-info-name"> 记录人 </div>
                        <div class="profile-info-value">
                            <span id="username">{{ post.author.username }}</span>
                        </div>
                    </div>
                    <div class="profile-info-row">
                        <div class="profile-info-name"> 公司名 </div>
                        <div class="profile-info-value">
                            <span id="username">{{ post.company_name }}</span>
                        </div>
                    </div>
                    <div class="profile-info-row">
                        <div class="profile-info-name"> 电话 </div>
                        <div class="profile-info-value">
                            <span id="username">{{ post.tel_no }}</span>
                        </div>
                    </div>
                    <div class="profile-info-row">
                        <div class="profile-info-name"> 咨询者 </div>
                        <div class="profile-info-value">
                            <span id="username">{{ post.consultee }}</span>
                        </div>
                    </div>
                    <div class="profile-info-row">
                        <div class="profile-info-name"> 所属行业 </div>
                        <div class="profile-info-value">
                            <span id="username">{{ post.category.name }}</span>
                        </div>
                    </div>
                    <div class="profile-info-row">
                        <div class="profile-info-name"> 咨询范围 </div>
                        <div class="profile-info-value">
                            <span id="username">
                                {% for name in post.tags.all %}
                                    {{ name }}
                                {% endfor %}</span>
                        </div>
                    </div>
                    <div class="profile-info-row">
                        <div class="profile-info-name"> 咨询内容 </div>
                        <div class="profile-info-value">
                            <span id="username">{{ post.content | safe}}</span>
                        </div>
                    </div>
                    <div class="profile-info-row">
                        <div class="profile-info-name"> 上门人员 </div>
                        <div class="profile-info-value">
                            <span id="username">{{ post.assign_person }}</span>
                        </div>
                    </div>
                    <div class="profile-info-row">
                        <div class="profile-info-name"> 咨询结果 </div>
                        <div class="profile-info-value">
                            <span id="username">{{ post.result }}</span>
                        </div>
                    </div>
                    <div class="profile-info-row">
                        <div class="profile-info-name"> 协议价单 </div>
                        <div class="profile-info-value">
                            <span id="username">{{ post.pricing }}</span>
                        </div>
                    </div>
                    <div class="profile-info-row">
                        <div class="profile-info-name"> 备注 </div>
                        <div class="profile-info-value">
                            <span id="username">{{ post.remarks }}</span>
                        </div>
                    </div>
                </div>
                {% if request.user == post.author %}
                    <div class="panel-footer">
                        {% if not post.published %}
                            <a href="{% url 'focus:edit_post' pk=post.pk %}"><span class="label label-success">编辑</span></a>
                        {% endif %}
                    </div>
                {% endif %}
                <div class="space-12"></div>

                <div class="center">
                    <span class="btn btn-app btn-sm btn-light no-hover">
                        <span class="line-height-1 bigger-170 blue"> {{ post.views }} </span>
                        <br />
                        <span class="line-height-1 smaller-90"> Views </span>
                    </span>
                    <span class="btn btn-app btn-sm btn-grey no-hover">
                        <span class="line-height-1 bigger-170"> {{ post.comment_set.count }} </span>

                        <br />
                        <span class="line-height-1 smaller-90"> Comments </span>
                    </span>
                </div>
                <div class="space-12"></div>
                <div class="widget-box transparent">
                    <div class="widget-header widget-header-small">
                        <h4 class="widget-title blue smaller">
                            <i class="icon-edit"></i>
                            最新评论
                        </h4>
                    </div>
                    <div class="widget-body">
                        <div class="widget-main padding-8">
                            <!-- #section:pages/profile.feed -->
                            <div id="profile-feed-1" class="profile-feed">
                                <div class="profile-activity clearfix">
                                    <div>
                                        {% if post.comment_set.count %}
                                            {% for comment in comment_list %}
                                                <a class="user" href="{% url 'focus:user_info' comment.user_id %}">{{ comment.user }}</a>
                                                {{ comment.content | safe}}
                                                <div class="time">
                                                    <i class="ace-icon fa fa-clock-o bigger-110"></i>
                                                    {{ comment.pub_date | naturaltime }}
                                                </div>
                                            {% endfor %}
                                        {% else %}
                                            {% if not comment_list %}
                                                <li class="list-group-item comment-item">Be the first to reply!</li>
                                            {% endif %}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="space-12"></div>

                <div class="panel panel-default">
                    <div class="panel-heading">添加评论</div>
                    <div class="panel-body">
                        {% if request.user.is_authenticated %}
                            <form action="{% url 'focus:detail' pk=post.pk %}" method="POST">
                                {% crispy form %}
                            </form>
                        {% else %}
                            <div class="alert alert-warning" role="alert">
                                {% url login_url_name as login_url %}
                                    Please <a href="{{ login_url }}">Login</a> to comment
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock main %}